version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - err113
    - errcheck
    - exhaustive
    - gochecknoglobals
    - goconst
    - gocritic
    - godot
    - godox
    - goheader
    - gomodguard
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - mnd
    - nakedret
    - nolintlint
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testpackage
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl_v5
  exclusions:
    rules:
      - linters:
          - mnd
        text: "Magic number: (2|0644)"